version: '3'
services:
  postgres:
    container_name: postgressqldb
    image: postgres:13
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - development

  redis:
    image: redis:alpine
    container_name: redisdb
    ports:
      - "${REDIS_PORT}:6379"
    profiles:
      - development

volumes:
  postgres_data: